---
- name: Install homebrew
  ansible.builtin.command: 
    cmd: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  environment:
    CI: "true"
  args:
    creates: /home/linuxbrew/.linuxbrew/bin/brew

- name: Install homebrew
  ansible.builtin.shell: |
    /bin/bash -c 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"'
  changed_when: true
  args:
    executable: /bin/bash

- name: Add homebrew to path
  ansible.builtin.lineinfile:
    become: true
    path: "{{ path_oh_my_zsh }}"
    line: 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"'
    state: present
  args:
    backup: true
    create: false
    insertafter: EOF
    regexp: '^eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"$'

