---
- name: Install requirements
  ansible.builtin.include_tasks: requirements.yml

- name: Install homebrew
  ansible.builtin.include_tasks: install_brew.yml

- name: Install packages tap
  community.general.homebrew_tap:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages_tap }}"

- name: Install packages
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages }}"
